In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\Abcom\Desktop\mlops_project\Data\archive\creditcard.csv")

In [3]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [8]:
df.shape

(284807, 31)

In [9]:
284807 - 1081

283726

In [6]:
df[df.duplicated()]

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
33,26.0,-0.529912,0.873892,1.347247,0.145457,0.414209,0.100223,0.711206,0.176066,-0.286717,...,0.046949,0.208105,-0.185548,0.001031,0.098816,-0.552904,-0.073288,0.023307,6.14,0
35,26.0,-0.535388,0.865268,1.351076,0.147575,0.433680,0.086983,0.693039,0.179742,-0.285642,...,0.049526,0.206537,-0.187108,0.000753,0.098117,-0.553471,-0.078306,0.025427,1.77,0
113,74.0,1.038370,0.127486,0.184456,1.109950,0.441699,0.945283,-0.036715,0.350995,0.118950,...,0.102520,0.605089,0.023092,-0.626463,0.479120,-0.166937,0.081247,0.001192,1.18,0
114,74.0,1.038370,0.127486,0.184456,1.109950,0.441699,0.945283,-0.036715,0.350995,0.118950,...,0.102520,0.605089,0.023092,-0.626463,0.479120,-0.166937,0.081247,0.001192,1.18,0
115,74.0,1.038370,0.127486,0.184456,1.109950,0.441699,0.945283,-0.036715,0.350995,0.118950,...,0.102520,0.605089,0.023092,-0.626463,0.479120,-0.166937,0.081247,0.001192,1.18,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282987,171288.0,1.912550,-0.455240,-1.750654,0.454324,2.089130,4.160019,-0.881302,1.081750,1.022928,...,-0.524067,-1.337510,0.473943,0.616683,-0.283548,-1.084843,0.073133,-0.036020,11.99,0
283483,171627.0,-1.464380,1.368119,0.815992,-0.601282,-0.689115,-0.487154,-0.303778,0.884953,0.054065,...,0.287217,0.947825,-0.218773,0.082926,0.044127,0.639270,0.213565,0.119251,6.82,0
283485,171627.0,-1.457978,1.378203,0.811515,-0.603760,-0.711883,-0.471672,-0.282535,0.880654,0.052808,...,0.284205,0.949659,-0.216949,0.083250,0.044944,0.639933,0.219432,0.116772,11.93,0
284191,172233.0,-2.667936,3.160505,-3.355984,1.007845,-0.377397,-0.109730,-0.667233,2.309700,-1.639306,...,0.391483,0.266536,-0.079853,-0.096395,0.086719,-0.451128,-1.183743,-0.222200,55.66,0
284193,172233.0,-2.691642,3.123168,-3.339407,1.017018,-0.293095,-0.167054,-0.745886,2.325616,-1.634651,...,0.402639,0.259746,-0.086606,-0.097597,0.083693,-0.453584,-1.205466,-0.213020,36.74,0

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df.shape

(283726, 31)

#### - It is Imbalance Dataset

In [14]:
df['Class'].value_counts(normalize=True) * 100

Class
0    99.83329
1     0.16671
Name: proportion, dtype: float64

### **Splitting the Dataset**

In [22]:
X = df.drop('Class',axis=1)
y = df['Class']

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,y,
    test_size=0.2,
    stratify=y, 
    random_state=42
)

In [24]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [26]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,283726.000000,283726.000000,283726.000000,283726.000000,283726.000000,283726.000000,283726.000000,283726.000000,283726.000000,283726.000000,...,283726.000000,283726.000000,283726.000000,283726.000000,283726.000000,283726.000000,283726.000000,283726.000000,283726.000000,283726.000000
mean,94811.077600,0.005917,-0.004135,0.001613,-0.002966,0.001828,-0.001139,0.001801,-0.000854,-0.001596,...,-0.000371,-0.000015,0.000198,0.000214,-0.000232,0.000149,0.001763,0.000547,88.472687,0.001667
std,47481.047891,1.948026,1.646703,1.508682,1.414184,1.377008,1.331931,1.227664,1.179054,1.095492,...,0.723909,0.724550,0.623702,0.605627,0.521220,0.482053,0.395744,0.328027,250.399437,0.040796
min,0.000000,-56.407510,-72.715728,-48.325589,-5.683171,-113.743307,-26.160506,-43.557242,-73.216718,-13.434066,...,-34.830382,-10.933144,-44.807735,-2.836627,-10.295397,-2.604551,-22.565679,-15.430084,0.000000,0.000000
25%,54204.750000,-0.915951,-0.600321,-0.889682,-0.850134,-0.689830,-0.769031,-0.552509,-0.208828,-0.644221,...,-0.228305,-0.542700,-0.161703,-0.354453,-0.317485,-0.326763,-0.070641,-0.052818,5.600000,0.000000
50%,84692.500000,0.020384,0.063949,0.179963,-0.022248,-0.053468,-0.275168,0.040859,0.021898,-0.052596,...,-0.029441,0.006675,-0.011159,0.041016,0.016278,-0.052172,0.001479,0.011288,22.000000,0.000000
75%,139298.000000,1.316068,0.800283,1.026960,0.739647,0.612218,0.396792,0.570474,0.325704,0.595977,...,0.186194,0.528245,0.147748,0.439738,0.350667,0.240261,0.091208,0.078276,77.510000,0.000000
max,172792.000000,2.454930,22.057729,9.382558,16.875344,34.801666,73.301626,120.589494,20.007208,15.594995,...,27.202839,10.503090,22.528412,4.584549,7.519589,3.517346,31.612198,33.847808,25691.160000,1.000000

In [28]:
X_train[['Amount','Time']]

        Amount      Time
226238   32.00  144549.0
134253    6.99   80716.0
186465   14.95  127116.0
149493   17.30   91342.0
18461    24.00   29522.0
...        ...       ...
225116  124.00  144113.0
3525    261.80    3013.0
242674   37.00  151594.0
60594     5.00   49395.0
67057    12.31   52346.0

[226980 rows x 2 columns]

In [29]:
X_train[['Amount','Time']] = scaler.fit_transform(X_train[['Amount','Time']])

In [32]:
X_train[['Amount','Time']]

          Amount      Time
226238 -0.229434  1.045499
134253 -0.331197 -0.298690
186465 -0.298809  0.678397
149493 -0.289247 -0.074929
18461  -0.261985 -1.376728
...          ...       ...
225116  0.144905  1.036318
3525    0.705600 -1.934952
242674 -0.209089  1.193852
60594  -0.339294 -0.958245
67057  -0.309550 -0.896103

[226980 rows x 2 columns]

In [34]:
X_test[['Amount','Time']]

        Amount      Time
86568    11.50   61290.0
251557    1.94  155394.0
20232    91.28   30881.0
68952   228.00   53203.0
191852    1.41  129429.0
...        ...       ...
56516     2.00   47464.0
188431    9.99  127974.0
115561    9.14   73912.0
187644    0.89  127623.0
8267     15.95   11067.0

[56746 rows x 2 columns]

In [35]:
X_test[['Amount','Time']] = scaler.transform(X_test[['Amount','Time']])

In [36]:
X_test[['Amount','Time']]

          Amount      Time
86568  -0.312846 -0.707761
251557 -0.351745  1.273872
20232   0.011771 -1.348111
68952   0.568071 -0.878056
191852 -0.353901  0.727104
...          ...       ...
56516  -0.351501 -0.998907
188431 -0.318990  0.696464
115561 -0.322449 -0.441968
187644 -0.356017  0.689073
8267   -0.294740 -1.765352

[56746 rows x 2 columns]

In [46]:
# Fit on Train
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

X_train_scaled[['Amount','Time']] = scaler.fit_transform(X_train[['Amount','Time']])

X_test_scaled[['Amount','Time']] = scaler.transform(X_test[['Amount','Time']])

In [47]:
lr.fit(X_train_scaled,y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [48]:
y_pred = lr.predict(X_test_scaled)
y_pred_prob = lr.predict_proba(X_test_scaled)[:,1]

In [49]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test,y_pred)

print(cm)

[[55258  1393]
 [   12    83]]

    [[TN FP]
    [FN TP]]

In [50]:
from sklearn.metrics import roc_auc_score

roc = roc_auc_score(y_test, y_pred_prob)

print(roc)

0.9658392242808925

In [ ]:
from sklearn.metrics import precision_recall_curve
import matplotlib.pyplot as plt

precision, recall, thresolds = precision_recall_curve(y_test, y_pred_prob)

plt.plot(recall, precision)

#### Why we should not do fit_transform on test dataset ?

- To avoid Data Leakage

In [ ]:
# Apply some Class Weights

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000, class_weight='balanced')
lr.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

array([0.02177687, 0.02032174, 0.01003082, ..., 0.04129319, 0.0458121 ,
       0.02693454], shape=(56746,))

In [41]:
# Predictions

y_pred = lr.predict(X_test)
y_pred_prob = lr.predict_proba(lr.predict_proba(X_test))[:,1] # Probability of Fraud (Class 1)

c:\Users\Abcom\anaconda3\envs\mlops_1_venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

ValueError: X has 2 features, but LogisticRegression is expecting 30 features as input.